### ISSUE TITLE
工作的时候提示

### ISSUE THREAD

**Issue by Greasen** [reactjser/vue3-virtual-scroll-list#1]
vue3-virtual-scroll-list is incorrectly packaged. Please contact the package author to fix.

**Comment by reactjser** [comment]
> vue3-virtual-scroll-list is incorrectly packaged. Please contact the package author to fix.

I didn't find this issue, could you please provide a repo?

**Comment by Greasen** [comment]
> > vue3-virtual-scroll-list 打包错误。请联系包作者修复。
> 
> 我无法复制，你能提供一个回购吗？

不好意思，我已经解决了
